apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs
  namespace: resourceallocation
spec:
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.98.159.44
    path: "/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-volume
  namespace: resourceallocation
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
