kind: ReplicationController
apiVersion: v1
metadata:
  name: resourceallocation
  namespace: resourceallocation
spec:
  replicas: 1
  selector:
    component: resourceallocation 
  template:
    metadata:
      labels:
        component: resourceallocation
    spec:
      containers:
        - name: resourceallocation
          image: sahandha/resourceallocation
          imagePullPolicy: Always
          command: ["/bin/sh"]
          args: ["-c","python /external/server/server.py"]
          ports:
            - containerPort: 27017
            - containerPort: 8888 
          volumeMounts:
            - mountPath: /external/shared
              name: volume
          resources:
            requests:
              cpu: 100m
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
