kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: resourceallocation
  name: resourceallocation
rules:
- apiGroups: ["","extensions"] # "" indicates the core API group
  resources: ["nodes", "namespaces", "resourcequotas", "limitranges", "pods","deployments","replicasets","replicationcontrollers", "ingresses", "configmaps","services","endpoints", "priorityclasses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
