kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: resourceallocation
  name: resourceallocation
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["nodes", "namespaces", "resourcequotas", "limitranges", "pods","deployments","deployment/extensions","replicasets","replicationcontrollers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
