kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: resourceallocation-binding
  namespace: resourceallocation
subjects:
- kind: ServiceAccount
  name: default
  namespace: resourceallocation
roleRef:
  kind: ClusterRole
  name: resourceallocation
  apiGroup: rbac.authorization.k8s.io
